In [62]:
import numpy as np
import pandas as pd

In [32]:
def make_array(start,length,step):
     b = np.arange(start, length*step,step)
     return b   

In [37]:
make_array(6,100,4)


array([  6,  10,  14,  18,  22,  26,  30,  34,  38,  42,  46,  50,  54,
        58,  62,  66,  70,  74,  78,  82,  86,  90,  94,  98, 102, 106,
       110, 114, 118, 122, 126, 130, 134, 138, 142, 146, 150, 154, 158,
       162, 166, 170, 174, 178, 182, 186, 190, 194, 198, 202, 206, 210,
       214, 218, 222, 226, 230, 234, 238, 242, 246, 250, 254, 258, 262,
       266, 270, 274, 278, 282, 286, 290, 294, 298, 302, 306, 310, 314,
       318, 322, 326, 330, 334, 338, 342, 346, 350, 354, 358, 362, 366,
       370, 374, 378, 382, 386, 390, 394, 398])

In [40]:
a = np.array([1,2,3,np.nan,5,6,7,np.nan])
nan_array = np.isnan(a)
not_nan_array = ~ nan_array
array2 = a[not_nan_array]
print(array2)

[1. 2. 3. 5. 6. 7.]


In [61]:
a = np.random.randint(1,101, size=(5,6))
print(a)
for i in range(5):
    print(a[i,].max())

[[ 72  11  67  74  14  44]
 [ 72  52  99   4  53  73]
 [ 43  47  64  76  36  33]
 [  8 100  73  54  25  23]
 [ 62   6  21  73  73  58]]
74
99
76
100
73


In [105]:
ser = pd.Series(np.take(list('abcdefghijklmnop'), np.random.randint(16, size=500)))
ser.head()
ser.value_counts()


n    37
f    37
e    36
k    35
m    34
d    33
p    33
j    32
a    32
b    31
o    31
i    30
c    27
g    26
h    24
l    22
dtype: int64

In [176]:
series = pd.Series(['01 Jan 2020', '10-19-2020', '20150303', '2013/04/04', '2012-05-05', '2013-06-06T12:20'])
# df = pd.DataFrame(series, columns=['dates'])
df['dates'] = pd.to_datetime(df['dates'], format='%Y%m%d')
df





ValueError: time data '01 Jan 2020' does not match format '%Y%m%d' (match)

In [115]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.head()


Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0        Acura  Integra    Small       12.9   15.9       18.8      25.0   
1          NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2         Audi       90  Compact       25.9   29.1       32.3      20.0   
3         Audi      100  Midsize        NaN   37.7       44.6      19.0   
4          BMW     535i  Midsize        NaN   30.0        NaN      22.0   

   MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0         31.0                None      Front  ...        5.0   177.0   
1         25.0  Driver & Passenger      Front  ...        5.0   195.0   
2         26.0         Driver only      Front  ...        5.0   180.0   
3         26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4         30.0                 NaN       Rear  ...        4.0   186.0   

   Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0      102.0   68.0         37.0           26.5           NaN  2705.0   
1      115.0   71.0         38.0           30.0          15.0  3560.0   
2      102.0   67.0         37.0           28.0          14.0  3375.0   
3      106.0    NaN         37.0           31.0          17.0  3405.0   
4      109.0   69.0         39.0           27.0          13.0  3640.0   

    Origin           Make  
0  non-USA  Acura Integra  
1  non-USA   Acura Legend  
2  non-USA        Audi 90  
3  non-USA       Audi 100  
4  non-USA       BMW 535i  

[5 rows x 27 columns]

In [116]:
len(df.columns)

27

In [119]:
df.rename(columns = {'Type': 'TypeOfCar'})

Manufacturer    Model TypeOfCar  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra     Small       12.9   15.9       18.8      25.0   
1           NaN   Legend   Midsize       29.2   33.9       38.7      18.0   
2          Audi       90   Compact       25.9   29.1       32.3      20.0   
3          Audi      100   Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i   Midsize        NaN   30.0        NaN      22.0   
..          ...      ...       ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan       Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat   Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado    Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240   Compact       21.8   22.7       23.5      21.0   
92          NaN      850   Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                None      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                None      Front  ...        7.0   187.0   
89         30.0                None      Front  ...        5.0   180.0   
90         25.0                None      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

In [122]:
del df['EngineSize']

In [128]:
df.drop(['Length'],axis=1)

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small       12.9   15.9       18.8      25.0   
1           NaN   Legend  Midsize       29.2   33.9       38.7      18.0   
2          Audi       90  Compact       25.9   29.1       32.3      20.0   
3          Audi      100  Midsize        NaN   37.7       44.6      19.0   
4           BMW     535i  Midsize        NaN   30.0        NaN      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van       16.6   19.7       22.7      17.0   
89   Volkswagen   Passat  Compact       17.6   20.0       22.4      21.0   
90   Volkswagen  Corrado   Sporty       22.9   23.3       23.7      18.0   
91        Volvo      240  Compact       21.8   22.7       23.5      21.0   
92          NaN      850  Midsize       24.8   26.7       28.5      20.0   

    MPG.highway             AirBags DriveTrain  ... Fuel.tank.capacity  \
0          31.0                None      Front  ...               13.2   
1          25.0  Driver & Passenger      Front  ...               18.0   
2          26.0         Driver only      Front  ...               16.9   
3          26.0  Driver & Passenger        NaN  ...               21.1   
4          30.0                 NaN       Rear  ...               21.1   
..          ...                 ...        ...  ...                ...   
88         21.0                None      Front  ...               21.1   
89         30.0                None      Front  ...               18.5   
90         25.0                None      Front  ...               18.5   
91         28.0         Driver only       Rear  ...               15.8   
92         28.0  Driver & Passenger      Front  ...               19.3   

    Passengers  Wheelbase  Width Turn.circle  Rear.seat.room  Luggage.room  \
0          5.0      102.0   68.0        37.0            26.5           NaN   
1          5.0      115.0   71.0        38.0            30.0          15.0   
2          5.0      102.0   67.0        37.0            28.0          14.0   
3          6.0      106.0    NaN        37.0            31.0          17.0   
4          4.0      109.0   69.0        39.0            27.0          13.0   
..         ...        ...    ...         ...             ...           ...   
88         7.0      115.0   72.0        38.0            34.0           NaN   
89         5.0      103.0   67.0        35.0            31.5          14.0   
90         4.0       97.0   66.0        36.0            26.0          15.0   
91         5.0      104.0   67.0        37.0            29.5          14.0   
92         5.0      105.0   69.0        38.0            30.0          15.0   

    Weight   Origin                Make  
0   2705.0  non-USA       Acura Integra  
1   3560.0  non-USA        Acura Legend  
2   3375.0  non-USA             Audi 90  
3   3405.0  non-USA            Audi 100  
4   3640.0  non-USA            BMW 535i  
..     ...      ...                 ...  
88  3960.0      NaN  Volkswagen Eurovan  
89  2985.0  non-USA   Volkswagen Passat  
90  2810.0  non-USA  Volkswagen Corrado  
91  2985.0  non-USA           Volvo 240  
92  3245.0  non-USA           Volvo 850  

[93 rows x 25 columns]

In [129]:
df1 = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.random.randint(0, 15, 9)})

df2 = pd.DataFrame({'pazham': ['apple', 'orange', 'pine'] * 2,
                    'kilo': ['high', 'low'] * 3,
                    'price': np.random.randint(0, 15, 6)})

In [140]:
result = df1.merge(df2, how = 'inner')
result

fruit  weight  price  pazham  kilo
0   apple    high      6   apple  high
1   apple    high      6   apple  high
2  orange     low      4  orange   low
3  banana  medium      4  orange   low
4  orange     low     10   apple   low
5  orange     low     14    pine   low

In [254]:
df = pd.DataFrame(["STD,City\tState",
"33,Kolkata\tWest Bengal",
"44,Chennai\tTamil Nadu",
"40,Hyderabad\tTelengana",
"80,Bangalore\tKarnataka"], columns=['row'])
df 


row
0          STD,City\tState
1  33,Kolkata\tWest Bengal
2   44,Chennai\tTamil Nadu
3  40,Hyderabad\tTelengana
4  80,Bangalore\tKarnataka

In [255]:
df =df.row.str.split(r',|\t',expand=True) 
df=df.drop([0])
df.columns =['STD','city','state']
df


STD       city        state
1  33    Kolkata  West Bengal
2  44    Chennai   Tamil Nadu
3  40  Hyderabad    Telengana
4  80  Bangalore    Karnataka

In [257]:
names = ["mpg", "cylinders", "displacement", "horsepower", "weight", "acceleration", "model_year", "origin", "car_name"]
df_mpg = pd.read_csv("auto-mpg.data", header=None, names=names, delim_whitespace=True)

FileNotFoundError: [Errno 2] No such file or directory: 'auto-mpg.data.csv'